deployment:
  tasks:
    # Set your deployment path
    - export DEPLOYPATH=/home1/spreaeb3/public_html/swapp-temp/

    # Sync all files, including dotfiles like .htaccess
    - /bin/rsync -av --delete --include=".*" ./ $DEPLOYPATH
