---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/spreaeb3/public_html/website_3d3e8e2b/
    - /bin/rsync -av --delete \
        --exclude '.git*' \
        --exclude '.cpanel.yml' \
        ./ $DEPLOYPATH
